protect against race conditions in package versions
We're getting rare, intermittent failures:
   AssertionError: Failed test: skymap in packages
This appears to be due to a race condition in writing the package verisons.
lsst.skymap is only imported before Task execution (and therefore subject to
having its version recorded) once: in makeSkyMap.py. If that runs at the same
time as something else that's updating the package versions, the skymap
package version could be overwritten. This patch forces skymap generation to
be done early, and in serial to avoid race conditions.